### ISSUE TITLE
Int64 timestamps

### ISSUE THREAD

**Issue by malware-unicorn** [djhohnstein/SharpChrome#1]
Chrome timestamps are appearing as negative numbers in cookie json due to integer overflow.

line 157 of SQLiteDatabase.cs change sqlite3_column_int to sqlite3_column_int64.
line 468 of Program.cs change expDate to account for webkit timestamp to unixepoch: ((expDate/1000000) - 11644473600).

Works great.

**Comment by djhohnstein** [comment]
This has been fixed in the latest commit along with some other miscellaneous error checking here: https://github.com/djhohnstein/SharpChrome/commit/c794d2196812b7b92de6d5d7c6f3b5900b16deca

Further, Will just pushed an update to SharpDPAPI to integrate some functionality of this project into his. His now allows for lock-less database reading (such that no temporary files need to be created), triage remote machines and decrypt any blob given the correct master key.  Usage can be found here: https://github.com/GhostPack/SharpDPAPI#sharpchrome

Thank you for the issue; it is clear, precise, and what every GitHub issue should strive to be.
