### ISSUE TITLE
Importing Cookies

### ISSUE THREAD

**Issue by OllyHill** [djhohnstein/SharpChrome#3]
Hello,

I wanted to better understand importing cookies. I can successfully write these cookies to a text file, but cannot import them into Chrome.

I've reviewed the output of cookies and have deleted the line that lists the current user (since this is not part of the JSON syntax for Chrome cookies), but still cannot import them. I've used ~4 different chrome cookie extensions without luck.

Do you have any recommendations on how to successfully import the cookies?

Cheers and loving this project,
Olly

**Comment by djhohnstein** [comment]
Hey Olly,

Thanks for the kind words. Last time I used this project I believed I used:

https://addons.mozilla.org/en-US/firefox/addon/a-cookie-manager/

Should be a simple import into that add-on within FireFox.


That said, modifying the cookie JSON output isn't too difficult if you have the stomach for it. It's something I've had to do time and time again because I too, frustratingly, have a difficult time finding an extension that isn't trash. For your favorite extension, dump the cookies for an arbitrary website. After you do that, look at the syntax and modify the functions defined within the following to get the proper output:

https://github.com/djhohnstein/SharpChrome/blob/master/Program.cs#L355

Rebuild and you should be set.

Best of luck!
